# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  day7-benchmarks:
    dependencies:
    - base
    - day7
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: day7 is a new Haskeleton package.
executables:
  day7:
    dependencies:
    - base
    - day7
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/day7
library:
  dependencies:
  - base
  - containers
  - attoparsec
  - text
  source-dirs: library
license: MIT
maintainer: Author name here
name: day7
synopsis: A new Haskeleton package.
tests:
  day7-test-suite:
    dependencies:
    - base
    - day7
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
